version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates managed by GitHub Actions once a month
      interval: "monthly"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      # Check for updates managed by npm once a month
      interval: "monthly"
    groups:
      # Group together all dependencies in a single pull request
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 30
    ignore:
      # https://github.com/advisories/GHSA-qq6h-5g6j-q3cm
      - dependency-name: "sweetalert2"
