name: portfolio

services:
    # https://hub.docker.com/_/varnish
    varnish:
        image: varnish:8
        restart: always
        volumes:
            - ./docker/configuration/default.vcl:/etc/varnish/default.vcl:ro
        depends_on:
            node:
                condition: service_healthy
        environment:
            VARNISH_SIZE: 128m
        healthcheck:
            test: wget -O - http://localhost/portfolio
            retries: 3
            timeout: 5s
        ports:
            - "80:80"

    # https://github.com/FlorianLeChat/Portfolio
    node:
        image: portfolio
        restart: always
        command: npm run start
        environment:
            TZ: ${TZ}
        healthcheck:
            test: wget -O - http://localhost:3000
            retries: 3
            timeout: 5s
        build:
            context: .
            dockerfile: ./docker/scripts/Dockerfile
        expose:
            - "3000"