name: portfolio

services:
    # https://hub.docker.com/_/varnish
    varnish:
        image: varnish:alpine
        restart: always
        depends_on:
            - node
        volumes:
            - ./docker/default.vcl:/etc/varnish/default.vcl:ro
        environment:
            VARNISH_SIZE: 128m
        healthcheck:
            test: wget -O - http://localhost/portfolio
            retries: 3
            timeout: 5s
        ports:
            - "80:80"

    # https://github.com/FlorianLeChat/Portfolio
    node:
        image: portfolio
        restart: always
        command: npm run start
        volumes:
            - ./logs:/usr/src/app/logs
        healthcheck:
            test: wget -O - http://localhost:3000
            retries: 3
            timeout: 5s
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        expose:
            - "3000"