name: portfolio

services:
    proxy:
        image: varnish:8-alpine
        restart: unless-stopped
        volumes:
            - ./varnish.vcl:/etc/varnish/default.vcl:ro
        cap_drop:
            - ALL
        depends_on:
            server:
                condition: service_healthy
        environment:
            VARNISH_SIZE: 128m
        security_opt:
            - no-new-privileges=true
        healthcheck:
            test: wget -O - http://localhost/
            retries: 3
            timeout: 5s
            start_period: 30s
        deploy:
            resources:
                limits:
                    pids: 1024
                    cpus: "0.5"
                    memory: 256M
        ports:
            - "${PORT:-80}:80"

    server:
        user: "${UID:-1000}:${GID:-1000}"
        image: registry.florian-dev.fr:443/floriantrayon/portfolio:${VERSION:-latest}
        restart: unless-stopped
        command: npm run start
        cap_drop:
            - ALL
        env_file:
            - .env
        environment:
            PORT: 3000
        security_opt:
            - no-new-privileges=true
        healthcheck:
            test: wget -O - http://localhost:3000/
            retries: 3
            timeout: 5s
            start_period: 30s
        deploy:
            resources:
                limits:
                    pids: 64
                    cpus: "1"
                    memory: 512M
        build:
            context: .
            dockerfile: ./docker/Dockerfile
