name: portfolio

services:
    # https://github.com/FlorianLeChat/Portfolio
    node:
        image: portfolio
        restart: always
        develop:
            watch:
                - action: sync
                  path: .
                  target: /usr/src/app
        healthcheck:
            test: wget -O - http://localhost:3000
            retries: 3
            timeout: 5s
        build:
            context: .
            dockerfile: ./docker/Dockerfile.${NEXT_PUBLIC_ENV}
        ports:
            - "3000:3000"