name: portfolio

version: "3.8"

services:
    # https://github.com/FlorianLeChat/Portfolio
    node:
        image: portfolio
        restart: always
        healthcheck:
            test: curl -f http://localhost:3000
            retries: 3
            timeout: 5s
        build:
            context: .
            dockerfile: ./docker/Dockerfile.${NEXT_PUBLIC_ENV}
        ports:
            - "3000:3000"