version: "3.9"

services:
  # https://github.com/FlorianLeChat/Portfolio
  node:
    image: portfolio
    container_name: website
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000