---
-   hosts: proxmox
    vars:
        environments:
            test: "/var/www/portfolio.test.florian-dev.fr"
            production: "/var/www/florian-dev.fr/portfolio"
        application_path: "{{ environments[deploy] }}"
    tasks:
        -   name: Installation des dépendances système
            apt:
                name:
                    - zip
                    - rsync
                state: present
                update_cache: true

        -   name: Création du répertoire d'installation
            file:
                path: "{{ application_path }}"
                state: directory
                mode: "0700"
                owner: debian
                group: debian

        -   name: Création du répertoire temporaire
            file:
                path: "{{ application_path }}_temp"
                state: directory
                mode: "0700"
                owner: debian
                group: debian

        -   name: Extraction des fichiers du projet dans le répertoire temporaire
            unarchive:
                src: "../../project.zip"
                dest: "{{ application_path }}_temp"
                remote_src: false
                keep_newer: true

        -   name: Synchronisation des fichiers avec suppression des fichiers obsolètes
            command: rsync -a --delete "{{ application_path }}_temp/" "{{ application_path }}/"

        -   name: Application des permissions sur les fichiers de variables d'environnement
            file:
                path: "{{ application_path }}/.env"
                mode: "0400"
                owner: debian
                group: debian

        -   name: Suppression du répertoire temporaire
            file:
                path: "{{ application_path }}_temp"
                state: absent

        -   name: Arrêt du conteneur Docker et suppression des ressources associées
            community.docker.docker_compose_v2:
                remove_orphans: true
                remove_images: all
                project_src: "{{ application_path }}"
                state: absent

        -   name: Démarrage du conteneur Docker
            community.docker.docker_compose_v2:
                renew_anon_volumes: true
                project_src: "{{ application_path }}"
                recreate: always
                build: never
                pull: always
