name: Docker Image CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 6 * * 1
  pull_request:
  workflow_dispatch:

jobs:
  codeql:
    uses: ./.github/workflows/codeql.yml

  playwright:
    uses: ./.github/workflows/playwright.yml

  eslint:
    uses: ./.github/workflows/eslint.yml

  build-image:
    runs-on: ubuntu-latest
    needs: [ codeql, playwright, eslint ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: latest=true
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image and push
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: .
